apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: booksapp
    project: booksapp
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"  # NPLB 설정
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"  # 성능을 DYNAMIC으로 설정
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"  # 외부 접근을 허용
    service.beta.kubernetes.io/ncloud-load-balancer-description: "BooksApp Webapp Service with NPLB"  # 로드 밸런서 설명 추가
    service.beta.kubernetes.io/ncloud-load-balancer-algorithm-type-code: "RR"  # Round Robin 방식으로 트래픽 분산
    service.beta.kubernetes.io/ncloud-load-balancer-idle-timeout: "60"  # Idle Timeout 설정 (초)
    service.beta.kubernetes.io/ncloud-load-balancer-enable-skip-acg-update: "false"  # ACG 업데이트 허용
spec:
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    app: webapp
